- name: get container status
  shell: docker ps -a -f name=my_container --format {%raw%}"table {{.Status}}"{%endraw%} | awk 'FNR == 2 {print}' | awk '{print $1}'
  register: status

- debug: msg="{{ status.stdout }}" 